name: Setup Node
runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".tool-versions"
    - uses: actions/cache@v4
      with:
        id: node_modules_cache_id
        path: node_modules
        key: node-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - run: pnpm i --frozen-lockfile
      if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      shell: bash
