media:
  input: src/assets/images
  output: ../../assets/images
content:
  - name: blog
    label: Blog
    type: collection
    path: src/data/blog/**
    view:
      fields: [ title, draft, publishDate, category, tags ]
      sort: [publishDate]
      search: [title, category]
      default: { sort: publishDate, order: desc }
    fields:
      - { name: publishDate, label: PublishDate, type: date }
      - { name: category, label: Category, type: select, options: { values: [tech, idea, life] } }
      - { name: title, label: Title, type: string, required: true }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }